[build-system]
requires = ["setuptools>=77", "numpy>=1.26"]
build-backend = "setuptools.build_meta"

[project]
name = "numeta"
version = "0.6.0"
description = "Numeta is a small transpiler for Python with a metaprogramming focus."
readme = "README.md"
authors = [
    { name = "Andrea Bianchi", email = "andrea_bianchi@outlook.com" }
]
license = "MIT"
requires-python = ">=3.12"

dependencies = [
    "numpy>=1.26"
]

[project.optional-dependencies]
dev = [
    "black==24.4.2",
    "build",
    "pre-commit",
    "pytest",
]

[tool.black]
line-length = 100
target-version = ["py312"]
